# Generated by Django 5.1.6 on 2026-03-21 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo total')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CoordinatorEmailConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('recipient_type', models.CharField(choices=[('TO', 'Principal'), ('CC', 'Copia')], default='TO', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_emails', to='programs.program')),
            ],
            options={
                'verbose_name': 'Configuración de coordinador',
                'verbose_name_plural': 'Configuraciones de coordinadores',
                'unique_together': {('program', 'email')},
            },
        ),
    ]
