# Generated by Django 5.1.6 on 2026-06-19 04:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio acordado')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('DROPPED', 'Retirado'), ('GRADUATED', 'Graduado')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='programs.program')),
                ('bootcamper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'unique_together': {('bootcamper', 'bootcamp')},
            },
        ),
    ]
