# Generated by Django 5.1.6 on 2026-08-02 23:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(verbose_name='Número de cohorte')),
                ('start_month', models.DateField(verbose_name='Mes de inicio')),
                ('end_month', models.DateField(blank=True, null=True, verbose_name='Mes de finalización')),
                ('status', models.CharField(choices=[('UPCOMING', 'Próximamente'), ('IN_PROGRESS', 'En curso'), ('FINISHED', 'Finalizada')], default='UPCOMING', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='programs.program', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Cohorte',
                'verbose_name_plural': 'Cohortes',
                'ordering': ['-start_month', '-number'],
                'constraints': [models.UniqueConstraint(fields=('program', 'number'), name='unique_cohort_number_per_program')],
            },
        ),
    ]
