# Generated by Django 5.1.6 on 2026-08-03 15:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_cohort_end_month_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Descuento (%)'),
        ),
    ]
