# Generated by Django 5.1.6 on 2026-08-03 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_enrollment_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='programs.cohort', verbose_name='Cohorte'),
        ),
    ]
