# Generated by Django 5.1.6 on 2026-08-07 23:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_enrollment_cohort'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('bootcamper', 'bootcamp', 'cohort'), name='unique_enrollment_per_cohort'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('cohort__isnull', True)), fields=('bootcamper', 'bootcamp'), name='unique_enrollment_per_program_without_cohort'),
        ),
    ]
