-- ============================================================
-- Boot-Tracker — DDL real de PostgreSQL 16
-- NO editar a mano. Volcado de la base tras `manage.py migrate`:
--
--   docker compose up -d db backend
--   docker compose exec -T backend python manage.py migrate
--   docker compose exec -T db pg_dump -U "$DB_USER" -d "$DB_NAME" \
--       --schema-only --no-owner --no-privileges \
--     | grep -v "^.restrict\|^.unrestrict" > docs/diagrams/database/schema.sql
--
-- Incluye las tablas internas de Django y de simplejwt (token_blacklist_*),
-- que erd.mmd y schema.dbml omiten a propósito.
-- ============================================================

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_customuser; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.authentication_customuser (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    id uuid NOT NULL,
    email character varying(254) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    phone character varying(20),
    role character varying(20) NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    cedula character varying(13),
    coordinator_scope character varying(20) NOT NULL,
    finance_assigned_at timestamp with time zone,
    finance_owner_id uuid,
    verification_status character varying(25) NOT NULL,
    verified_by_id uuid,
    verified_at timestamp with time zone,
    onboarding_completed_at timestamp with time zone,
    onboarding_token_issued_at timestamp with time zone,
    verification_rejection_reason text NOT NULL,
    data_consent_at timestamp with time zone,
    data_consent_version character varying(20) NOT NULL
);


--
-- Name: authentication_customuser_coordinator_programs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.authentication_customuser_coordinator_programs (
    id bigint NOT NULL,
    customuser_id uuid NOT NULL,
    program_id uuid NOT NULL
);


--
-- Name: authentication_customuser_coordinator_programs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.authentication_customuser_coordinator_programs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_customuser_coordinator_programs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_customuser_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.authentication_customuser_groups (
    id bigint NOT NULL,
    customuser_id uuid NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: authentication_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.authentication_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_customuser_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.authentication_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id uuid NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: authentication_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.authentication_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: leads_interaction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.leads_interaction (
    id uuid NOT NULL,
    interaction_type character varying(20) NOT NULL,
    outcome character varying(30) NOT NULL,
    interest_level integer,
    notes text NOT NULL,
    campaign character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    salesperson_id uuid NOT NULL,
    lead_id uuid NOT NULL,
    duration_minutes integer,
    next_action text NOT NULL,
    next_action_date date,
    lead_status character varying(20),
    CONSTRAINT leads_interaction_duration_minutes_check CHECK ((duration_minutes >= 0))
);


--
-- Name: leads_lead; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.leads_lead (
    id uuid NOT NULL,
    name character varying(200) NOT NULL,
    phone character varying(20) NOT NULL,
    email character varying(254),
    program_interest character varying(200) NOT NULL,
    source character varying(20) NOT NULL,
    is_company boolean NOT NULL,
    status character varying(30) NOT NULL,
    assigned_at timestamp with time zone,
    version integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    owner_id uuid,
    program_id uuid,
    last_contact timestamp with time zone,
    deleted_at timestamp with time zone,
    released_at timestamp with time zone,
    bootcamper_id uuid,
    discard_detail text NOT NULL,
    discard_reason character varying(20) NOT NULL,
    discarded_at timestamp with time zone,
    discarded_by_id uuid,
    status_before_discard character varying(30) NOT NULL,
    CONSTRAINT leads_lead_version_check CHECK ((version >= 0))
);


--
-- Name: leads_leadassignmentsetting; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.leads_leadassignmentsetting (
    id bigint NOT NULL,
    self_assign_enabled boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    updated_by_id uuid
);


--
-- Name: leads_leadassignmentsetting_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.leads_leadassignmentsetting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leads_leadassignmentsetting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meetings_meeting; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.meetings_meeting (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    google_event_id character varying(255),
    created_at timestamp with time zone NOT NULL,
    assigned_to_id uuid,
    lead_id uuid NOT NULL
);


--
-- Name: meetings_meeting_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.meetings_meeting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meetings_meeting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments_bootcamperassignmentsetting; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments_bootcamperassignmentsetting (
    id bigint NOT NULL,
    self_assign_enabled boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    updated_by_id uuid
);


--
-- Name: payments_bootcamperassignmentsetting_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments_bootcamperassignmentsetting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_bootcamperassignmentsetting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments_payment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments_payment (
    id uuid NOT NULL,
    receipt_file character varying(100) NOT NULL,
    receipt_file_type character varying(10) NOT NULL,
    ocr_bank_name character varying(200) NOT NULL,
    ocr_account_last_digits character varying(10) NOT NULL,
    ocr_amount numeric(12,2),
    ocr_transaction_id character varying(100) NOT NULL,
    ocr_raw_text text NOT NULL,
    confirmed_amount numeric(12,2),
    confirmed_bank_name character varying(200) NOT NULL,
    confirmed_transaction_id character varying(100) NOT NULL,
    status character varying(10) NOT NULL,
    rejection_reason text NOT NULL,
    validated_at timestamp with time zone,
    submitted_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    bootcamper_id uuid NOT NULL,
    program_id uuid NOT NULL,
    validated_by_id uuid,
    ocr_payment_date date,
    ocr_confidence jsonb NOT NULL,
    payer_name character varying(200) NOT NULL,
    payer_identification character varying(20) NOT NULL,
    payer_email character varying(254) NOT NULL,
    payer_address character varying(255) NOT NULL,
    payer_phone character varying(20) NOT NULL,
    document_number character varying(50) NOT NULL,
    payment_method character varying(10) NOT NULL,
    payment_link_id uuid,
    deleted_at timestamp with time zone,
    deleted_by_id uuid
);


--
-- Name: payments_paymentlink; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments_paymentlink (
    id uuid NOT NULL,
    url character varying(200) NOT NULL,
    amount numeric(12,2),
    note character varying(200) NOT NULL,
    status character varying(10) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    created_by_id uuid,
    enrollment_id uuid NOT NULL
);


--
-- Name: payments_paymentplan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments_paymentplan (
    id uuid NOT NULL,
    file character varying(100) NOT NULL,
    file_type character varying(10) NOT NULL,
    original_name character varying(255) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    bootcamper_id uuid NOT NULL,
    uploaded_by_id uuid
);


--
-- Name: programs_cohort; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.programs_cohort (
    id uuid NOT NULL,
    number integer NOT NULL,
    start_month date NOT NULL,
    end_month date NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    program_id uuid NOT NULL,
    CONSTRAINT programs_cohort_number_check CHECK ((number >= 0))
);


--
-- Name: programs_coordinatoremailconfig; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.programs_coordinatoremailconfig (
    id uuid NOT NULL,
    email character varying(254) NOT NULL,
    name character varying(200) NOT NULL,
    recipient_type character varying(2) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    program_id uuid NOT NULL
);


--
-- Name: programs_enrollment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.programs_enrollment (
    id uuid NOT NULL,
    start_date date NOT NULL,
    agreed_price numeric(10,2) NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    bootcamp_id uuid NOT NULL,
    bootcamper_id uuid NOT NULL,
    discount_percentage numeric(5,2) NOT NULL,
    cohort_id uuid
);


--
-- Name: programs_program; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.programs_program (
    id uuid NOT NULL,
    name character varying(200) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    total_cost numeric(10,2) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id uuid,
    jti character varying(255) NOT NULL
);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authentication_customuser_groups authentication_customuse_customuser_id_group_id_8a637646_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_customuser_groups
    ADD CONSTRAINT authentication_customuse_customuser_id_group_id_8a637646_uniq UNIQUE (customuser_id, group_id);


--
-- Name: authentication_customuser_user_permissions authentication_customuse_customuser_id_permission_923704b1_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_customuser_user_permissions
    ADD CONSTRAINT authentication_customuse_customuser_id_permission_923704b1_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: authentication_customuser_coordinator_programs authentication_customuse_customuser_id_program_id_acdfd235_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_customuser_coordinator_programs
    ADD CONSTRAINT authentication_customuse_customuser_id_program_id_acdfd235_uniq UNIQUE (customuser_id, program_id);


--
-- Name: authentication_customuser authentication_customuser_cedula_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_customuser
    ADD CONSTRAINT authentication_customuser_cedula_key UNIQUE (cedula);


--
-- Name: authentication_customuser_coordinator_programs authentication_customuser_coordinator_programs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_customuser_coordinator_programs
    ADD CONSTRAINT authentication_customuser_coordinator_programs_pkey PRIMARY KEY (id);


--
-- Name: authentication_customuser authentication_customuser_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_customuser
    ADD CONSTRAINT authentication_customuser_email_key UNIQUE (email);


--
-- Name: authentication_customuser_groups authentication_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_customuser_groups
    ADD CONSTRAINT authentication_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: authentication_customuser authentication_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_customuser
    ADD CONSTRAINT authentication_customuser_pkey PRIMARY KEY (id);


--
-- Name: authentication_customuser_user_permissions authentication_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_customuser_user_permissions
    ADD CONSTRAINT authentication_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: leads_interaction leads_interaction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leads_interaction
    ADD CONSTRAINT leads_interaction_pkey PRIMARY KEY (id);


--
-- Name: leads_lead leads_lead_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leads_lead
    ADD CONSTRAINT leads_lead_pkey PRIMARY KEY (id);


--
-- Name: leads_leadassignmentsetting leads_leadassignmentsetting_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leads_leadassignmentsetting
    ADD CONSTRAINT leads_leadassignmentsetting_pkey PRIMARY KEY (id);


--
-- Name: meetings_meeting meetings_meeting_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meetings_meeting
    ADD CONSTRAINT meetings_meeting_pkey PRIMARY KEY (id);


--
-- Name: payments_bootcamperassignmentsetting payments_bootcamperassignmentsetting_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_bootcamperassignmentsetting
    ADD CONSTRAINT payments_bootcamperassignmentsetting_pkey PRIMARY KEY (id);


--
-- Name: payments_payment payments_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_pkey PRIMARY KEY (id);


--
-- Name: payments_paymentlink payments_paymentlink_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_paymentlink
    ADD CONSTRAINT payments_paymentlink_pkey PRIMARY KEY (id);


--
-- Name: payments_paymentplan payments_paymentplan_bootcamper_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_paymentplan
    ADD CONSTRAINT payments_paymentplan_bootcamper_id_key UNIQUE (bootcamper_id);


--
-- Name: payments_paymentplan payments_paymentplan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_paymentplan
    ADD CONSTRAINT payments_paymentplan_pkey PRIMARY KEY (id);


--
-- Name: programs_cohort programs_cohort_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs_cohort
    ADD CONSTRAINT programs_cohort_pkey PRIMARY KEY (id);


--
-- Name: programs_coordinatoremailconfig programs_coordinatoremailconfig_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs_coordinatoremailconfig
    ADD CONSTRAINT programs_coordinatoremailconfig_pkey PRIMARY KEY (id);


--
-- Name: programs_coordinatoremailconfig programs_coordinatoremailconfig_program_id_email_dad98e2d_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs_coordinatoremailconfig
    ADD CONSTRAINT programs_coordinatoremailconfig_program_id_email_dad98e2d_uniq UNIQUE (program_id, email);


--
-- Name: programs_enrollment programs_enrollment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs_enrollment
    ADD CONSTRAINT programs_enrollment_pkey PRIMARY KEY (id);


--
-- Name: programs_program programs_program_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs_program
    ADD CONSTRAINT programs_program_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: programs_cohort unique_cohort_number_per_program; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs_cohort
    ADD CONSTRAINT unique_cohort_number_per_program UNIQUE (program_id, number);


--
-- Name: programs_enrollment unique_enrollment_per_cohort; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs_enrollment
    ADD CONSTRAINT unique_enrollment_per_cohort UNIQUE (bootcamper_id, bootcamp_id, cohort_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authentication_customuser__customuser_id_33d2a5f7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authentication_customuser__customuser_id_33d2a5f7 ON public.authentication_customuser_user_permissions USING btree (customuser_id);


--
-- Name: authentication_customuser__customuser_id_79d11b4c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authentication_customuser__customuser_id_79d11b4c ON public.authentication_customuser_coordinator_programs USING btree (customuser_id);


--
-- Name: authentication_customuser__permission_id_e47332af; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authentication_customuser__permission_id_e47332af ON public.authentication_customuser_user_permissions USING btree (permission_id);


--
-- Name: authentication_customuser__program_id_f8daa797; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authentication_customuser__program_id_f8daa797 ON public.authentication_customuser_coordinator_programs USING btree (program_id);


--
-- Name: authentication_customuser_cedula_c5ac52bb_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authentication_customuser_cedula_c5ac52bb_like ON public.authentication_customuser USING btree (cedula varchar_pattern_ops);


--
-- Name: authentication_customuser_email_a127f886_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authentication_customuser_email_a127f886_like ON public.authentication_customuser USING btree (email varchar_pattern_ops);


--
-- Name: authentication_customuser_finance_owner_id_d6317b37; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authentication_customuser_finance_owner_id_d6317b37 ON public.authentication_customuser USING btree (finance_owner_id);


--
-- Name: authentication_customuser_groups_customuser_id_a7d1343c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authentication_customuser_groups_customuser_id_a7d1343c ON public.authentication_customuser_groups USING btree (customuser_id);


--
-- Name: authentication_customuser_groups_group_id_c5ef1d10; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authentication_customuser_groups_group_id_c5ef1d10 ON public.authentication_customuser_groups USING btree (group_id);


--
-- Name: authentication_customuser_verified_by_id_710035b3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authentication_customuser_verified_by_id_710035b3 ON public.authentication_customuser USING btree (verified_by_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: leads_interaction_lead_id_3d739f31; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX leads_interaction_lead_id_3d739f31 ON public.leads_interaction USING btree (lead_id);


--
-- Name: leads_interaction_salesperson_id_c2d41ca1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX leads_interaction_salesperson_id_c2d41ca1 ON public.leads_interaction USING btree (salesperson_id);


--
-- Name: leads_lead_bootcamper_id_630fcfad; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX leads_lead_bootcamper_id_630fcfad ON public.leads_lead USING btree (bootcamper_id);


--
-- Name: leads_lead_created_at_a7f0123f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX leads_lead_created_at_a7f0123f ON public.leads_lead USING btree (created_at);


--
-- Name: leads_lead_deleted_at_36222eb8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX leads_lead_deleted_at_36222eb8 ON public.leads_lead USING btree (deleted_at);


--
-- Name: leads_lead_discarded_by_id_8f03c8c6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX leads_lead_discarded_by_id_8f03c8c6 ON public.leads_lead USING btree (discarded_by_id);


--
-- Name: leads_lead_owner_id_1f4568d0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX leads_lead_owner_id_1f4568d0 ON public.leads_lead USING btree (owner_id);


--
-- Name: leads_lead_program_id_c1414041; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX leads_lead_program_id_c1414041 ON public.leads_lead USING btree (program_id);


--
-- Name: leads_lead_status_a2927927; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX leads_lead_status_a2927927 ON public.leads_lead USING btree (status);


--
-- Name: leads_lead_status_a2927927_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX leads_lead_status_a2927927_like ON public.leads_lead USING btree (status varchar_pattern_ops);


--
-- Name: leads_leadassignmentsetting_updated_by_id_a0f48f59; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX leads_leadassignmentsetting_updated_by_id_a0f48f59 ON public.leads_leadassignmentsetting USING btree (updated_by_id);


--
-- Name: meetings_meeting_assigned_to_id_df931bc0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX meetings_meeting_assigned_to_id_df931bc0 ON public.meetings_meeting USING btree (assigned_to_id);


--
-- Name: meetings_meeting_lead_id_8238593e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX meetings_meeting_lead_id_8238593e ON public.meetings_meeting USING btree (lead_id);


--
-- Name: payments_bootcamperassignmentsetting_updated_by_id_62f6c733; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_bootcamperassignmentsetting_updated_by_id_62f6c733 ON public.payments_bootcamperassignmentsetting USING btree (updated_by_id);


--
-- Name: payments_payment_bootcamper_id_c351e782; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_payment_bootcamper_id_c351e782 ON public.payments_payment USING btree (bootcamper_id);


--
-- Name: payments_payment_deleted_at_2872162b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_payment_deleted_at_2872162b ON public.payments_payment USING btree (deleted_at);


--
-- Name: payments_payment_deleted_by_id_ab28f4fe; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_payment_deleted_by_id_ab28f4fe ON public.payments_payment USING btree (deleted_by_id);


--
-- Name: payments_payment_payment_link_id_90356efb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_payment_payment_link_id_90356efb ON public.payments_payment USING btree (payment_link_id);


--
-- Name: payments_payment_program_id_43a5766b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_payment_program_id_43a5766b ON public.payments_payment USING btree (program_id);


--
-- Name: payments_payment_status_fc8cbda2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_payment_status_fc8cbda2 ON public.payments_payment USING btree (status);


--
-- Name: payments_payment_status_fc8cbda2_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_payment_status_fc8cbda2_like ON public.payments_payment USING btree (status varchar_pattern_ops);


--
-- Name: payments_payment_submitted_at_7607cba2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_payment_submitted_at_7607cba2 ON public.payments_payment USING btree (submitted_at);


--
-- Name: payments_payment_validated_by_id_81a2d18e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_payment_validated_by_id_81a2d18e ON public.payments_payment USING btree (validated_by_id);


--
-- Name: payments_paymentlink_created_at_ddc1de88; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_paymentlink_created_at_ddc1de88 ON public.payments_paymentlink USING btree (created_at);


--
-- Name: payments_paymentlink_created_by_id_20142064; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_paymentlink_created_by_id_20142064 ON public.payments_paymentlink USING btree (created_by_id);


--
-- Name: payments_paymentlink_enrollment_id_1b809d01; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_paymentlink_enrollment_id_1b809d01 ON public.payments_paymentlink USING btree (enrollment_id);


--
-- Name: payments_paymentlink_status_2906689e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_paymentlink_status_2906689e ON public.payments_paymentlink USING btree (status);


--
-- Name: payments_paymentlink_status_2906689e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_paymentlink_status_2906689e_like ON public.payments_paymentlink USING btree (status varchar_pattern_ops);


--
-- Name: payments_paymentplan_uploaded_by_id_f6321243; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_paymentplan_uploaded_by_id_f6321243 ON public.payments_paymentplan USING btree (uploaded_by_id);


--
-- Name: programs_cohort_program_id_9e54ebe6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX programs_cohort_program_id_9e54ebe6 ON public.programs_cohort USING btree (program_id);


--
-- Name: programs_coordinatoremailconfig_program_id_b9db77a9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX programs_coordinatoremailconfig_program_id_b9db77a9 ON public.programs_coordinatoremailconfig USING btree (program_id);


--
-- Name: programs_enrollment_bootcamp_id_8b8c1ba4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX programs_enrollment_bootcamp_id_8b8c1ba4 ON public.programs_enrollment USING btree (bootcamp_id);


--
-- Name: programs_enrollment_bootcamper_id_2bd87f45; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX programs_enrollment_bootcamper_id_2bd87f45 ON public.programs_enrollment USING btree (bootcamper_id);


--
-- Name: programs_enrollment_cohort_id_d3fb0bc0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX programs_enrollment_cohort_id_d3fb0bc0 ON public.programs_enrollment USING btree (cohort_id);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: unique_enrollment_per_program_without_cohort; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX unique_enrollment_per_program_without_cohort ON public.programs_enrollment USING btree (bootcamper_id, bootcamp_id) WHERE (cohort_id IS NULL);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_customuser_user_permissions authentication_custo_customuser_id_33d2a5f7_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_customuser_user_permissions
    ADD CONSTRAINT authentication_custo_customuser_id_33d2a5f7_fk_authentic FOREIGN KEY (customuser_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_customuser_coordinator_programs authentication_custo_customuser_id_79d11b4c_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_customuser_coordinator_programs
    ADD CONSTRAINT authentication_custo_customuser_id_79d11b4c_fk_authentic FOREIGN KEY (customuser_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_customuser_groups authentication_custo_customuser_id_a7d1343c_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_customuser_groups
    ADD CONSTRAINT authentication_custo_customuser_id_a7d1343c_fk_authentic FOREIGN KEY (customuser_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_customuser authentication_custo_finance_owner_id_d6317b37_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_customuser
    ADD CONSTRAINT authentication_custo_finance_owner_id_d6317b37_fk_authentic FOREIGN KEY (finance_owner_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_customuser_groups authentication_custo_group_id_c5ef1d10_fk_auth_grou; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_customuser_groups
    ADD CONSTRAINT authentication_custo_group_id_c5ef1d10_fk_auth_grou FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_customuser_user_permissions authentication_custo_permission_id_e47332af_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_customuser_user_permissions
    ADD CONSTRAINT authentication_custo_permission_id_e47332af_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_customuser_coordinator_programs authentication_custo_program_id_f8daa797_fk_programs_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_customuser_coordinator_programs
    ADD CONSTRAINT authentication_custo_program_id_f8daa797_fk_programs_ FOREIGN KEY (program_id) REFERENCES public.programs_program(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_customuser authentication_custo_verified_by_id_710035b3_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authentication_customuser
    ADD CONSTRAINT authentication_custo_verified_by_id_710035b3_fk_authentic FOREIGN KEY (verified_by_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: leads_interaction leads_interaction_lead_id_3d739f31_fk_leads_lead_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leads_interaction
    ADD CONSTRAINT leads_interaction_lead_id_3d739f31_fk_leads_lead_id FOREIGN KEY (lead_id) REFERENCES public.leads_lead(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: leads_interaction leads_interaction_salesperson_id_c2d41ca1_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leads_interaction
    ADD CONSTRAINT leads_interaction_salesperson_id_c2d41ca1_fk_authentic FOREIGN KEY (salesperson_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: leads_lead leads_lead_bootcamper_id_630fcfad_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leads_lead
    ADD CONSTRAINT leads_lead_bootcamper_id_630fcfad_fk_authentic FOREIGN KEY (bootcamper_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: leads_lead leads_lead_discarded_by_id_8f03c8c6_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leads_lead
    ADD CONSTRAINT leads_lead_discarded_by_id_8f03c8c6_fk_authentic FOREIGN KEY (discarded_by_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: leads_lead leads_lead_owner_id_1f4568d0_fk_authentication_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leads_lead
    ADD CONSTRAINT leads_lead_owner_id_1f4568d0_fk_authentication_customuser_id FOREIGN KEY (owner_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: leads_lead leads_lead_program_id_c1414041_fk_programs_program_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leads_lead
    ADD CONSTRAINT leads_lead_program_id_c1414041_fk_programs_program_id FOREIGN KEY (program_id) REFERENCES public.programs_program(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: leads_leadassignmentsetting leads_leadassignment_updated_by_id_a0f48f59_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leads_leadassignmentsetting
    ADD CONSTRAINT leads_leadassignment_updated_by_id_a0f48f59_fk_authentic FOREIGN KEY (updated_by_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: meetings_meeting meetings_meeting_assigned_to_id_df931bc0_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meetings_meeting
    ADD CONSTRAINT meetings_meeting_assigned_to_id_df931bc0_fk_authentic FOREIGN KEY (assigned_to_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: meetings_meeting meetings_meeting_lead_id_8238593e_fk_leads_lead_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meetings_meeting
    ADD CONSTRAINT meetings_meeting_lead_id_8238593e_fk_leads_lead_id FOREIGN KEY (lead_id) REFERENCES public.leads_lead(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_bootcamperassignmentsetting payments_bootcampera_updated_by_id_62f6c733_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_bootcamperassignmentsetting
    ADD CONSTRAINT payments_bootcampera_updated_by_id_62f6c733_fk_authentic FOREIGN KEY (updated_by_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_payment payments_payment_bootcamper_id_c351e782_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_bootcamper_id_c351e782_fk_authentic FOREIGN KEY (bootcamper_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_payment payments_payment_deleted_by_id_ab28f4fe_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_deleted_by_id_ab28f4fe_fk_authentic FOREIGN KEY (deleted_by_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_payment payments_payment_payment_link_id_90356efb_fk_payments_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_payment_link_id_90356efb_fk_payments_ FOREIGN KEY (payment_link_id) REFERENCES public.payments_paymentlink(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_payment payments_payment_program_id_43a5766b_fk_programs_program_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_program_id_43a5766b_fk_programs_program_id FOREIGN KEY (program_id) REFERENCES public.programs_program(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_payment payments_payment_validated_by_id_81a2d18e_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_validated_by_id_81a2d18e_fk_authentic FOREIGN KEY (validated_by_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_paymentlink payments_paymentlink_created_by_id_20142064_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_paymentlink
    ADD CONSTRAINT payments_paymentlink_created_by_id_20142064_fk_authentic FOREIGN KEY (created_by_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_paymentlink payments_paymentlink_enrollment_id_1b809d01_fk_programs_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_paymentlink
    ADD CONSTRAINT payments_paymentlink_enrollment_id_1b809d01_fk_programs_ FOREIGN KEY (enrollment_id) REFERENCES public.programs_enrollment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_paymentplan payments_paymentplan_bootcamper_id_5f52f0a6_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_paymentplan
    ADD CONSTRAINT payments_paymentplan_bootcamper_id_5f52f0a6_fk_authentic FOREIGN KEY (bootcamper_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_paymentplan payments_paymentplan_uploaded_by_id_f6321243_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_paymentplan
    ADD CONSTRAINT payments_paymentplan_uploaded_by_id_f6321243_fk_authentic FOREIGN KEY (uploaded_by_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: programs_cohort programs_cohort_program_id_9e54ebe6_fk_programs_program_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs_cohort
    ADD CONSTRAINT programs_cohort_program_id_9e54ebe6_fk_programs_program_id FOREIGN KEY (program_id) REFERENCES public.programs_program(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: programs_coordinatoremailconfig programs_coordinator_program_id_b9db77a9_fk_programs_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs_coordinatoremailconfig
    ADD CONSTRAINT programs_coordinator_program_id_b9db77a9_fk_programs_ FOREIGN KEY (program_id) REFERENCES public.programs_program(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: programs_enrollment programs_enrollment_bootcamp_id_8b8c1ba4_fk_programs_program_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs_enrollment
    ADD CONSTRAINT programs_enrollment_bootcamp_id_8b8c1ba4_fk_programs_program_id FOREIGN KEY (bootcamp_id) REFERENCES public.programs_program(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: programs_enrollment programs_enrollment_bootcamper_id_2bd87f45_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs_enrollment
    ADD CONSTRAINT programs_enrollment_bootcamper_id_2bd87f45_fk_authentic FOREIGN KEY (bootcamper_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: programs_enrollment programs_enrollment_cohort_id_d3fb0bc0_fk_programs_cohort_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs_enrollment
    ADD CONSTRAINT programs_enrollment_cohort_id_d3fb0bc0_fk_programs_cohort_id FOREIGN KEY (cohort_id) REFERENCES public.programs_cohort(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--


