# Generated by Django 5.1.6 on 2026-03-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Cédula'),
        ),
    ]
