# Generated by Django 5.1.6 on 2026-06-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SALESPERSON', 'Vendedor'), ('BOOTCAMPER', 'Bootcamper'), ('ADMINISTRATOR', 'Administrador'), ('COORDINATOR', 'Coordinador'), ('FINANCE', 'Finanzas')], default='BOOTCAMPER', max_length=20, verbose_name='Rol'),
        ),
    ]
