# Generated by Django 5.1.6 on 2026-08-02 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_role'),
        ('programs', '0002_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coordinator_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_users', to='programs.program', verbose_name='Programa asignado'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='coordinator_scope',
            field=models.CharField(blank=True, choices=[('GENERAL', 'General'), ('PROGRAM', 'Por programa')], default='', max_length=20, verbose_name='Alcance del coordinador'),
        ),
    ]
