# Generated by Django 5.1.6 on 2026-08-03 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_coordinator_programs_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='finance_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='finance_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitored_bootcampers', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de cobro'),
        ),
    ]
