# Generated by Django 5.1.6 on 2026-08-05 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_rejection_reason',
            field=models.TextField(blank=True, verbose_name='Motivo del rechazo de verificación'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_status',
            field=models.CharField(choices=[('INVITED', 'Invitado'), ('PENDING_VERIFICATION', 'Pendiente de verificación'), ('VERIFIED', 'Verificado'), ('REJECTED', 'Rechazado')], default='VERIFIED', max_length=25, verbose_name='Estado de verificación'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_bootcampers', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
    ]
