# Generated by Django 5.1.6 on 2026-08-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_customuser_verification_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='data_consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consentimiento de datos'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='data_consent_version',
            field=models.CharField(blank=True, max_length=20, verbose_name='Versión del consentimiento'),
        ),
    ]
