# Generated by Django 5.1.6 on 2026-08-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_confirm_activated_bootcampers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_status',
            field=models.CharField(choices=[('INVITED', 'Invitado'), ('PENDING_VERIFICATION', 'Pendiente de verificación'), ('VERIFIED', 'Cuenta activa'), ('REJECTED', 'Rechazado')], default='VERIFIED', max_length=25, verbose_name='Estado de verificación'),
        ),
    ]
