# Generated by Django 5.1.6 on 2026-03-21 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('program_interest', models.CharField(blank=True, max_length=200, verbose_name='Programa de interés')),
                ('source', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp'), ('LANDING_PAGE', 'Landing Page'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20, verbose_name='Fuente')),
                ('is_company', models.BooleanField(default=False, verbose_name='Es empresa')),
                ('status', models.CharField(choices=[('NEW', 'Nuevo'), ('CONTACTED', 'Contactado'), ('INTERESTED', 'Interesado'), ('NOT_INTERESTED', 'No interesado'), ('SPEAK_COORDINATOR', 'Hablar con coordinador'), ('CONVERTED', 'Convertido')], default='NEW', max_length=30, verbose_name='Estado')),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor asignado')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('CALL', 'Llamada'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('NOTE', 'Nota')], max_length=20)),
                ('outcome', models.CharField(choices=[('INTERESTED', 'Interesado'), ('NOT_INTERESTED', 'No interesado'), ('NO_ANSWER', 'No contestó'), ('CALLBACK', 'Llamar después'), ('SPEAK_COORDINATOR', 'Hablar con coordinador')], max_length=30)),
                ('interest_level', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('campaign', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Interacción',
                'verbose_name_plural': 'Interacciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
