# Generated by Django 5.1.6 on 2026-06-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_interaction_fields_and_last_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Eliminado'),
        ),
    ]
