# Generated by Django 5.1.6 on 2026-06-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nuevo'), ('CONTACTED', 'Contactado'), ('QUALIFIED', 'Calificado'), ('INTERESTED', 'Interesado'), ('NOT_INTERESTED', 'No interesado'), ('SPEAK_COORDINATOR', 'Hablar con coordinador'), ('CONVERTED', 'Convertido')], default='NEW', max_length=30, verbose_name='Estado'),
        ),
    ]
