# Generated by Django 5.1.6 on 2026-07-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_migrate_contacted_to_interested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='outcome',
            field=models.CharField(choices=[('CALL_AGAIN', 'Llamar de nuevo'), ('SEND_INFO', 'Enviar información'), ('SCHEDULE_VISIT', 'Agendar visita'), ('AWAIT_REPLY', 'Esperar respuesta'), ('SPEAK_COORDINATOR', 'Hablar con coordinador')], max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nuevo'), ('QUALIFIED', 'Calificado'), ('INTERESTED', 'Interesado'), ('NOT_INTERESTED', 'No interesado'), ('CONVERTED', 'Convertido')], default='NEW', max_length=30, verbose_name='Estado'),
        ),
    ]
