# Generated by Django 5.1.6 on 2026-07-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_leadassignmentsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('CALL', 'Llamada'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('VISIT', 'Visita'), ('NOTE', 'Nota'), ('SYSTEM', 'Sistema')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='outcome',
            field=models.CharField(choices=[('CALL_AGAIN', 'Llamar de nuevo'), ('SEND_INFO', 'Enviar información'), ('SCHEDULE_VISIT', 'Agendar visita'), ('AWAIT_REPLY', 'Esperar respuesta'), ('SPEAK_COORDINATOR', 'Hablar con coordinador'), ('REASSIGNED', 'Reasignado por administrador')], max_length=30),
        ),
    ]
