# Generated by Django 5.1.6 on 2026-07-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_interaction_interaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Liberado'),
        ),
    ]
