# Generated by Django 5.1.6 on 2026-08-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_released_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nuevo'), ('QUALIFIED', 'Calificado'), ('INTERESTED', 'Interesado'), ('NOT_INTERESTED', 'No interesado'), ('CONVERTED', 'Convertido')], db_index=True, default='NEW', max_length=30, verbose_name='Estado'),
        ),
    ]
