# Generated by Django 5.1.6 on 2026-08-07 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_merge_bootcamper_link_and_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='discard_detail',
            field=models.TextField(blank=True, verbose_name='Detalle del descarte'),
        ),
        migrations.AddField(
            model_name='lead',
            name='discard_reason',
            field=models.CharField(blank=True, choices=[('NO_BUDGET', 'Sin presupuesto'), ('SCHEDULE', 'Los horarios no le sirven'), ('NO_RESPONSE', 'No responde / los correos rebotan'), ('FREE_ONLY', 'Sólo busca contenido gratis'), ('OTHER', 'Otro')], max_length=20, verbose_name='Motivo del descarte'),
        ),
        migrations.AddField(
            model_name='lead',
            name='discarded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Descartado'),
        ),
        migrations.AddField(
            model_name='lead',
            name='discarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discarded_leads', to=settings.AUTH_USER_MODEL, verbose_name='Descartado por'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status_before_discard',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='outcome',
            field=models.CharField(choices=[('CALL_AGAIN', 'Llamar de nuevo'), ('SEND_INFO', 'Enviar información'), ('SCHEDULE_VISIT', 'Agendar visita'), ('AWAIT_REPLY', 'Esperar respuesta'), ('SPEAK_COORDINATOR', 'Hablar con coordinador'), ('REASSIGNED', 'Reasignado por administrador'), ('DISCARDED', 'Descartado'), ('RESTORED', 'Reactivado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nuevo'), ('QUALIFIED', 'Calificado'), ('INTERESTED', 'Interesado'), ('NOT_INTERESTED', 'No interesado'), ('CONVERTED', 'Convertido'), ('DISCARDED', 'Descartado')], db_index=True, default='NEW', max_length=30, verbose_name='Estado'),
        ),
    ]
