# Generated by Django 5.1.6 on 2026-03-21 19:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_file', models.FileField(upload_to='receipts/%Y/%m/')),
                ('receipt_file_type', models.CharField(max_length=10)),
                ('ocr_bank_name', models.CharField(blank=True, max_length=200)),
                ('ocr_account_last_digits', models.CharField(blank=True, max_length=10)),
                ('ocr_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ocr_transaction_id', models.CharField(blank=True, max_length=100)),
                ('ocr_raw_text', models.TextField(blank=True)),
                ('confirmed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('confirmed_bank_name', models.CharField(blank=True, max_length=200)),
                ('confirmed_transaction_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bootcamper', models.ForeignKey(limit_choices_to={'role': 'BOOTCAMPER'}, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='programs.program')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
