# Generated by Django 5.1.6 on 2026-08-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_add_billing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'En revisión'), ('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
